{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vlagent-backend.fullname" . }}-upload
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploadSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vlagent-backend.fullname" . }}-download
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloadSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vlagent-backend.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logsSize }}
{{- end }}
